name: "ci"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run lint
      - run: npm run test:ci
      - name: Rebuild
        run: |
          npm run build

      - name: Commit prettier changes
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: "fix: rebuild"
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
